import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '../components/Providers'
import 'bootstrap-icons/font/bootstrap-icons.css'
import MainHeader from '../components/MainHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} min-h-screen bg-white min-w-screen dark:text-zinc-400 dark:bg-zinc-950 text-zinc-600 `}>
				<main className=''>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	)
}
