import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '../components/Providers'
import 'bootstrap-icons/font/bootstrap-icons.css'
import MainHeader from '../components/MainHeader'
import MainFooter from '../components/MainFooter'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<Script src='https://www.googletagmanager.com/gtag/js?id=G-T73PYN72WM' />
			<Script id='google-analytics'>
				{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', 'G-T73PYN72WM');
        `}
			</Script>
			<body
				className={`${inter.className} min-h-screen bg-white min-w-screen dark:text-zinc-400 dark:bg-zinc-950 text-zinc-600 `}>
				<main className=''>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	)
}
