// Generated by https://quicktype.io

export interface IOrder {
	_id: string
	shippingFee: number
	subtotal: number
	total: number
	orderItems: OrderItem[]
	status: string
	user: string
	clientSecret: string
	createdAt: string
	updatedAt: string
	__v: number
}

export interface OrderItem {
	quantity: number
	title: string
	_id: string
	price: number
	image: string
}
